# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meniu', '0002_auto_20160708_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='datta',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
