# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Meniu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.DateTimeField(verbose_name='date published')),
                ('phone', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=200)),
                ('desert', models.CharField(max_length=200)),
                ('id_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meniu.Menu')),
            ],
        ),
    ]
